using System;
using LibApi.Services.Contacts;
using LibShared;

namespace LibTest
{
	public class ContactTest
	{
        [Fact]
        public async void NewContactAutoGenerated()
        {
            Contact? contact = await Contact.CreateAsync(null, "BASTARAUD", "Loïc", "Nicolas", null, new DateTime(1994, 09, 28));
            if (contact != null)
            {
                //...
            }

            Assert.NotNull(contact);
        }
    }
}

